POST http://localhost:2525/imposters
Content-Type: application/json

{
    "name":"Exercicio0",
    "port":4500,
    "protocol":"http"
    
}

###
GET http://localhost:4501
Content-Type: application/json