POST http://localhost:2525/imposters
Content-Type: application/json

{
    "port":4501,
    "protocol":"http",
    "name":"Exercicio1",

    "stubs":[{
        "responses": [
            { "is": { "statusCode": 200,
                "body":{"Marcas":["Nissan",
                                  "Koeniggsegg",
                                  "Lamborghini",
                                  "Ford"]}}}],
        "predicates": [{
            "and": [
                    {
                    "equals": {
                        "path": "/api/marcas",
                        "method": "GET",
                        "headers": { "Content-Type": "application/json" }
                        }
                        },
                    {
                    "not": {
                        "contains": { "body": "requiredField" },
                        "caseSensitive": true
                    }
                }
            ]
        }]
    }]
}

###
GET http://localhost:4502/api/marcas
Content-Type: application/json