POST http://localhost:2525/imposters
content-Type: application/json

{
   "port":4508,
   "protocol":"http",
   "name":"Exercicio8",
   "stubs":[
      {
         "responses":[
            {
               "is":{
                  "statusCode":201,
                  "headers":{
                     "Content-Type":"application/json"
                  },
                  "body":{
                     "status":"created"
                  }
               }
            }
         ],
         "predicates":[
            {
               "equals":{
                  "path":"/api/temperature",
                  "method":"POST"
               }
            },
            {
                "contains":{
                    "body":{
                    "value":"string",
                    "sensor_id":"1"
                    }
                  
               }
            }
         ]
      }
   ]
}

###
POST http://localhost:4508/api/temperature
content-Type: application/json

{"value":"string"}